<font color=green size=6>
<b>Lectura desde APIs y .csv | 13.May.2024</b>
</font>

In [1]:
'''
Escribe una función que, dado un número indeterminado de números, devuelva dos cosas: 
- 1. La suma de los mismos. 
- 2. El valor mayor. Recuerda escribirlo de dos formas, con y sin return.   '''

def numeros(*nums):
    suma = 0
    for numero in nums:
        suma += numero
    
    numero_Mayor = 0
    for i in nums:
        if i > numero_Mayor:
            numero_Mayor = i
    mensaje = print(f'La suma de los números {nums} es: {suma} \ny el mayor es: {numero_Mayor}')
    return mensaje

numeros(1, 5, 14, 9, 18)

La suma de los números (1, 5, 14, 9, 18) es: 47
y el mayor es: 18

<font color=green size=4>
<b><u>USO DE APIs:</u></b>
</font>

In [2]:
import urllib
import json

http_request = urllib.request.urlopen("https://data.sfgov.org/resource/qz8r-q5ne.json")
 
#Leemos los datos de la url.
datos = http_request.read()
 
#conversión a json
datos_json = json.loads(datos)
# datos_json

In [3]:
suma = 0
conteo = 0

for elemento in datos_json:
    if 'average_speed_of_answer_in_secs' in elemento:
        suma += float(elemento['average_speed_of_answer_in_secs'])
        conteo += 1

media = suma / conteo

print(f'La media es: {media:.2f}')

La media es: 79.93

In [4]:
''' API:
USO. https://data.sfgov.org/resource/qz8r-q5ne.json '''

import pandas as pd

df_data = pd.read_json('https://data.sfgov.org/resource/qz8r-q5ne.json')
df_data

,month,inbound_calls,average_speed_of_answer_in_secs,abandoned_calls,call_abandonment_rate,in_person_visits
0,2024-04-01T00:00:00.000,3036,95.0,298.0,8.7,33.0
1,2024-03-01T00:00:00.000,2784,61.0,148.0,5.0,26.0
2,2024-02-01T00:00:00.000,3271,161.0,335.0,9.1,8.0
3,2024-01-01T00:00:00.000,4677,293.0,752.0,13.7,40.0
4,2023-12-01T00:00:00.000,2015,144.0,212.0,9.4,26.0
...,...,...,...,...,...,...
155,2011-05-01T00:00:00.000,3559,49.0,130.0,1.3,996.0
156,2011-04-01T00:00:00.000,6009,29.0,110.0,1.8,1527.0
157,2011-03-01T00:00:00.000,4379,29.0,72.0,2.1,820.0
158,2011-02-01T00:00:00.000,2520,18.0,30.0,1.4,676.0
159,2011-01-01T00:00:00.000,3171,25.0,45.0,1.4,862.0

In [5]:
media = df_data['average_speed_of_answer_in_secs'].mean()
print(f'La media es: {media:.2f}')

La media es: 79.93

In [6]:
import pandas as pd

df_CallCenter = pd.read_csv('Call_Center_Metrics_for_the_Health_Service_System_20240513.csv')
df_CallCenter

,Month,Inbound Calls,Average Speed of Answer in Secs,Abandoned Calls,Call Abandonment Rate,In-person visits
0,May 2023,3596,NaN,729.0,16.9,0
1,Apr 2023,3375,NaN,650.0,16.1,0
2,Mar 2023,4692,NaN,653.0,13.9,0
3,Feb 2023,2581,NaN,605.0,12.8,0
4,Jan 2023,2482,NaN,2091.0,25.0,0
...,...,...,...,...,...,...
144,May 2011,3559,49.0,130.0,1.3,996
145,Apr 2011,6009,29.0,110.0,1.8,1527
146,Mar 2011,4379,29.0,72.0,2.1,820
147,Feb 2011,2520,18.0,30.0,1.4,676
148,Jan 2011,3171,25.0,45.0,1.4,862

In [7]:
media_C = df_CallCenter['Average Speed of Answer in Secs'].mean()
print(f'La media es: {media_C:.2f}')

La media es: 63.96

In [10]:
import csv

suma = 0
conteo = 0
 
with open('Call_Center_Metrics_for_the_Health_Service_System_20240513.csv', 'r') as archivo_csv:
    # Crea un objeto lector CSV. Genera diccionario por linea
    lector_csv = csv.DictReader(archivo_csv)

    for fila in lector_csv:
        if fila['Average Speed of Answer in Secs'].strip():
            suma += float(fila['Average Speed of Answer in Secs'])
            conteo += 1

media = suma / conteo

print(f'La media es: {media:.2f}')

La media es: 63.96